language: node_js
node_js:
  - 10.11.0
services:
  - postgresql
before_script:
  - psql -c 'drop database if exists travis;' -U postgres
  - psql -c 'create database travis;' -U postgres
script:
  - yarn run test:server
after_success:
env:
  secure: smQb0Le15Ij5VRnOrDIBqyfE6zop4nh4n90dBThQtWcSuoqcDlzsyOiTv0SARO3uQcW3oGNHXM34yX1XUBEeAOyrz8R/RGEC00Y28TxtmWmphFnOLN4LTRA+J+OFWAhy+6IfRvCIZkfl1ioLYUvtyy6H0pupejj9F4NlzktUxA4DlGVQqXfn0JGASHRTO6/AVF3ILfOvk419YLf+WNkmXbALmgsxD908Om0WAjLE/hva4hfOxgB48VYhY0QLiWTx1RFBCejeCdofjpWLiufsWvfkl1rrwL320EvIHurzmWJP4IvQ4wz5h/TLOgSl+tHOjjbJvFnexu02A23Y4RC7yjfrlqen5fecD2xA6K1m/cYMBWQBSKPFB21ZjYq7W5xkEAZPQFfO7cvcOxeC1+xUNBhbTX3mDk66tcenpw831GRIUxs2mL6PDlTcijwHv9yQwuge0v1BU55O+6+tE1nu2Q5Qa3t0540r5DZrXk111HPsPyeRs3ZgSIAuDBLJNaQ7lNh8/hce48o0iaKTA0pswO0OlOxO2cFI1VkZFP5kiz4M8Ldq4TFh7515n5dQpeK/MEP6pbCIxGwsEMsN2PVqwn9aFLvLGn6YfWNk+I/dLFwnHHd/puYptqdSAxZ9wENJjWoCxCYwuRHBcpkqPdfiUQB00545x0+s901ivp26yUU=
